### ISSUE TITLE
this is a Error?

### ISSUE THREAD

**Issue by GoXian** [phfaustini/TfidfVectorizer#1]
arma::mat X_transformed(this->vocabulary_.size(), documents.size()); 
this is a Error?
I think should is "arma::mat X_transformed(documents.size(), this->vocabulary_.size()); "

**Comment by phfaustini** [comment]
Hi,

No, it's not wrong. Refer to Readme:

    Features are in rows, documents (objects) are in columns.
    This behavior is opposed to what is normally done in Python, but it is the default in C++ libraries such as MLPack.

**Comment by GoXian** [comment]
X_transformed(w, d) = tf_hash[word] * idf;
            else
                X_transformed(w, d) = (tf_hash[word] > 0) ? 1 : 0;

**Comment by GoXian** [comment]
You are Right !
